### ISSUE TITLE
Auction server URI config param in samples

### ISSUE THREAD

**Issue by maciejkowalczyk** [android/privacy-sandbox-samples#101]
Docs for FLEDGE Java samples [say](https://github.com/android/privacy-sandbox-samples/tree/dev-preview-main/Fledge/FledgeJava#launching-the-app):
> 1. Set your key value server endpoint
> ```
> adb shell "device_config put adservices ad_selection_data_auction_key_fetch_uri [your key fetch endpoint uri]"
> ```

It seems that the actual config param name is `fledge_auction_server_auction_key_fetch_uri` (like docs for Java PAS samples [suggest](https://github.com/android/privacy-sandbox-samples/tree/dev-preview-main/Fledge/SignalsJava#sample-app-for-signals-api))

**Comment by cshmerling** [comment]
Sorry for the late response- you are correct, `fledge_auction_server_auction_key_fetch_uri` is the proper param. The README was showing an older version, but has since been updated/
