### ISSUE TITLE
How to see the logs of SDK, when its running its SDK Runtime

### ISSUE THREAD

**Issue by hellosagar** [android/privacy-sandbox-samples#15]
I've tried running the client app in debug mode to see if the logs from the `sdk-app` are being printed in the app or not, but there is no log in the console. What is the way to actually see the logs in the console from the `sdk-app`.

Example code snippet

```
@SuppressLint("Override")
  @Override
  public void initSdk(
      SandboxedSdkContext sandboxedSdkContext,
      Bundle params,
      Executor executor,
      InitSdkCallback initSdkCallback
  ) {
    Log.d("initSDk", Thread.currentThread().getName());
    executor.execute(() ->
        initSdkCallback.onInitSdkFinished(new Bundle())
    );
  }

  @SuppressLint("Override")
  @Override
  public View getView(Context windowContext, Bundle bundle) {
    Log.d("getView", Thread.currentThread().getName());
    WebView webView = new WebView(windowContext);
    webView.loadUrl("https://developer.android.com/privacy-sandbox");
    return webView;
  }
```

**Comment by cshmerling** [comment]
You should be able to see the logs in logcat. You might need to play around with the filter as the logs come from the com.google.android.sdksandbox package (so I just cleared my filter and searched the logs for my string)
i.e.
![image](https://user-images.githubusercontent.com/106990149/182932474-e59bd972-dbcc-4cf7-810e-1acf5b7a085a.png)

**Comment by cshmerling** [comment]
Are you seeing any errors in logcat?

**Comment by hellosagar** [comment]
@cshmerling thanks again, In the console of the run tab it was not showing but in the section log after removing the specific package or after adding `com.google.android.sdksandbox` package it's showing the SDK one

<img width="1081" alt="Screenshot 2022-08-05 at 1 08 26 AM" src="https://user-images.githubusercontent.com/50016799/182938275-31c9be34-9553-4927-98ca-61a6c04784a3.png">
