### ISSUE TITLE
Unable to launch activity from sdk process

### ISSUE THREAD

**Issue by felixzhang0703** [android/privacy-sandbox-samples#16]
I'd like to start an activity from SDK process, but below error occurs:
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/35441627/183297538-454e443e-c35f-49ec-af34-65e9ea9fd9bb.png">
Seems there is a **"com.google.android.sdksandbox"** added to my activity intent. 
Any thoughts about how to launch an activity from SDK process?

**Comment by robclifford27** [comment]
Hey @felixzhang0703 I can take a look at this for you. Can you provide me with the following:
-What revision of the SDK are you running?
-What revision of the emulator images is installed on your device?
-If you can repro the issue consistently, can you capture an adb bugreport and upload it to our [IssueTracker](https://issuetracker.google.com/issues/new?component=1116743&template=1629474)

**Comment by robclifford27** [comment]
Additionally, can you provide some more information about the use case that you're trying to test here? Are you just following along with the README instructions or testing different things on your own?

**Comment by felixzhang0703** [comment]
Hi @robclifford27 , thanks for your time. 
The context is that as a monetization SDK, we want to show our ad activity from SDK runtime. That's why I did the test.
I'm using this sample project, adding a dummy MainActivity in "sdk-app" project, and try to start this activity from "onDataReceived".
This issue can be reproduced consistently on both pixel 4 TiramisuPrivacySandbox emulator and pixel 6 android 13 device. 
IssueTracker link: https://issuetracker.google.com/issues/241819499

<img width="909" alt="image" src="https://user-images.githubusercontent.com/35441627/183554866-64003a44-3bdf-4218-ae06-9e8b50cee4f6.png">

**Comment by siran-work** [comment]
@felixzhang0703 Moving forward, all the communications will be exchanged through the public bug. Thank you!

**Comment by cshmerling** [comment]
Going to mark this issue as resolved as there hasn't been activity here for awhile
