### ISSUE TITLE
Attribution Reporting not working

### ISSUE THREAD

**Issue by typerat** [android/privacy-sandbox-samples#17]
Hi,
We're having trouble getting Attribution Reporting to work correctly. Specifically, the server doesn't receive any reports. We followed the steps outlined in the [Readme](https://github.com/android/privacy-sandbox-samples/tree/main/AttributionReporting/MeasurementSampleApp#steps-to-test).
Registering sources and triggers looks like it's working - the server receives requests as expected. However, after setting the date forward, nothing happens. From what we read in the docs, we'd expect reports to be sent to the server.
Any help would be appreciated!

**Comment by cshmerling** [comment]
Apologies for the super delayed response- we did just publish a new Developer Preview as well as iterations of the sample apps. Can you update to the latest and let us know if you are still experiencing the issue?

**Comment by typerat** [comment]
Hey @cshmerling,
thanks for your response! I've tried the new examples (new features, yay 🥳). However, the server still doesn't receive any reports. I'm trying to find out if there's anything wrong with our setup or with our expectations. We're running the server on its own TLD+1, since the URL is `inferred from the eTLD+1 of servers used for accepting source registration and trigger registration` according to the docs. (side note: which of them is it actually? source or trigger?)
When should we expect the reports to arrive on the server? Immediately after setting the clock? Or is there an additional delay?

**Comment by erintwalsh** [comment]
Hi @typerat! 
To address your side question, the same URL accepts both source and trigger registrations. In our MeasurementAdTechServer sample code, we configure the URL to [accept source](https://github.com/android/privacy-sandbox-samples/blob/main/AttributionReporting/MeasurementAdTechServer/src/main/kotlin/com/example/samples/measurement/server/Application.kt#L148) as [url]/source?ad_id=[value], and [accept trigger](https://github.com/android/privacy-sandbox-samples/blob/main/AttributionReporting/MeasurementAdTechServer/src/main/kotlin/com/example/samples/measurement/server/Application.kt#L177) as [url]/trigger?conv_id=[value], where [url] is the same each time. 

To receive event-level and aggregate reporting, please try running this adb command to force the AttributionJobService before setting your clock:

- `adb shell cmd jobscheduler run -f com.google.android.adservices.api 5`

Then set your clock forward 3 days

Then run these two adb commands to force the ReportingJobService:

- `adb shell cmd jobscheduler run -f com.google.android.adservices.api 3`
- `adb shell cmd jobscheduler run -f com.google.android.adservices.api 7`

Then check to see if you have received your reports. 

If you are still having trouble after trying these steps, please let us know! Thank you so much for using Attribution Reporting!

**Comment by typerat** [comment]
Hi @erintwalsh,

thank you so much - I got a report now after sending this command sequence 🥳 
Should the [Readme](https://github.com/android/privacy-sandbox-samples/tree/main/AttributionReporting/MeasurementSampleApp#steps-to-test) be updated?

**Comment by erintwalsh** [comment]
Hi @typerat, I'm glad to hear it! Yes, the README has been updated. Please let us know if you run into any more issues!

**Comment by erintwalsh** [comment]
Hi @typerat, that's great to hear! Yes, the README has been updated. Please let us know if you run into any more issues!

**Comment by typerat** [comment]
Thanks again!
