### ISSUE TITLE
[Topics] Caller is not authorized to call this API. Caller is not allowed

### ISSUE THREAD

**Issue by g123k** [android/privacy-sandbox-samples#23]
Hello,

I've tried the sample app with the Topics project.
Before launching the app, I have setup my device (a Pixel 5a) by running the following commands:

```
adb shell device_config put adservices ppapi_app_allow_list \"*\"
adb shell setprop debug.adservices.topics_epoch_job_period_ms 300000
adb shell getprop debug.adservices.topics_epoch_job_period_ms
adb shell cmd jobscheduler run -f com.google.android.adservices.api 2
```

For the last command, I often have the following error:
`Could not find job 2 in package com.google.android.adservices.api / user 0`

But sometimes, it's OK and I can see it being taken into account:
`09-11 09:45:20.291  2145  3649 D JobScheduler: executeRunCommand(): com.google.android.adservices.api/0 2 s=false f=true`

And when running the sample app, I have the following error: `Caller is not authorized to call this API. Caller is not allowed``
![1](https://user-images.githubusercontent.com/246838/189517252-c068a4ea-9431-42bf-b1bd-33b9874a4bf9.png)

I have also tried with the emulator and I face exactly the same kind of issues, whichever project I use (the Kotlin or Java one)

**Comment by cshmerling** [comment]
Thanks for testing things out!

While we look in to this, can you confirm the following details:
1. For the device image and the emulator image, are you using the latest released? Emulator image should be revision 7
2. Are you using the latest SDK version? Should also be revision 7
3. Have you made any changes to the sample app, or are you running it as is?

**Comment by g123k** [comment]
Hi, 

Here are my answers below:

> Thanks for testing things out!
> 
> While we look in to this, can you confirm the following details:
> 
> 1. For the device image and the emulator image, are you using the latest released? Emulator image should be revision 7
I don't know where I can check this info, but no update is available both for the emulator and the device image (brand new installation)

> 2. Are you using the latest SDK version? Should also be revision 7
Yes: 
<img width="701" alt="Screenshot 2022-09-12 at 19 12 14" src="https://user-images.githubusercontent.com/246838/189715493-3d529bc2-e750-401f-933d-dbaf6fd26fb2.png">


> 3. Have you made any changes to the sample app, or are you running it as is?
No, I haven't touched anything

**Comment by 4ndR3d** [comment]
Could you try running the app before the commands then run 
```
adb shell device_config put adservices ppapi_app_allow_list \"*\"
```

Then run the rest of the commands

**Comment by g123k** [comment]
> cmd jobscheduler run -f com.google.android.adservices.api 2

There's still the same error (caller is not authorized)

**Comment by robclifford27** [comment]
@g123k Hey Edouard, thank you for being patient while we work on resolving this for you. Can you please try the following steps: 
-Create a new virtual device using the latest privacy sandbox emulator image revision
-Deploy the sample app to the device and open it (At this point you should see the caller not authorized message) 
-Close the app (But do not uninstall it from the emulator), and run: adb shell device_config put adservices ppapi_app_allow_list \"*\"
-Open the app up and let us know if you get the same message.

**Comment by g123k** [comment]
@robclifford27 Thanks, it now works!

The README file should be updated to prevent other testers to do the same mistake as me 👼 

![Screenshot_20221004_111432](https://user-images.githubusercontent.com/246838/193782175-e459966a-8768-42d5-af61-51c0083e53ce.png)
