### ISSUE TITLE
Unable to install the client-app for Privacy Sandbox Kotlin

### ISSUE THREAD

**Issue by hellosagar** [android/privacy-sandbox-samples#26]
During the installation of `client-app` facing this error

```
09/29 17:42:20: Launching 'client-app' on Pixel 4 API TiramisuPrivacySandbox.
Installation did not succeed.
The application could not be installed: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED

List of apks:
[0] '/Users/sagarkhurana/AndroidStudioProjects/privacy-sandbox-samples/PrivacySandboxKotlin/client-app/build/intermediates/apk/oem/debug/client-app-oem-debug.apk'
Installation failed due to: 'Failed to commit install session 1125088163 with command package install-commit 1125088163. Error: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl1125088163.tmp/base.apk (at Binary XML file line #67): Depending on multiple versions of SDK library com.example.privacysandbox.provider'
Retry
Failed to launch an application on all devices
```

Using Android Studio
```
Android Studio Flamingo | 2022.2.1 Canary 1
Build #AI-222.3739.54.2221.9043926, built on September 9, 2022
Runtime version: 11.0.15+0-b2043.56-8887301 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.5.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    ide.instant.shutdown=false

Non-Bundled Plugins:
    wu.seal.tool.jsontokotlin (3.7.4)
    some.awesome (1.14)
    de.netnexus.camelcaseplugin (3.0.12)
    google-java-format (1.15.0.0)
    com.github.setial (4.0.2)
    com.github.copilot (1.1.31.1908)
    com.facebook.ktfmt_idea_plugin (1.1.0.40)
    VisualVMLauncher (1.21.211.6085.0)
    Gradle View (4.0.0)
    com.chuntung.plugin.gistsnippet (1.1.0)
    zielu.gittoolbox (212.9.9)
    com.developerphil.adbidea (1.6.8)
```

**Comment by siran-work** [comment]
Thanks for reaching out to us! Is this the first time you try to install the app? If not, try to uninstall the app first before installing it on your device.

**Comment by hellosagar** [comment]
Yes, I've tested it on a freshly wiped out emulator, and still facing the same issue mentioned above

**Comment by cshmerling** [comment]
@hellosagar Are you using the command line to install the client app?
With Flamingo, it may be easier to install the client... let me just verify the instructions for that really quick

**Comment by hellosagar** [comment]
I've installed the `client-app` and `sdk-app ` using the Android Studio (not using the terminal)

**Comment by cshmerling** [comment]
Starting with a clean emulator, can you try editing the run configuration for the client app as such:

Go to Run > Edit Configurations. The Run/Debug Configuration window appears.
Under Launch Options, set Launch to Specified Activity
Click the three dot menu  next to Activity and select the Main Activity for your client
Click Apply and then OK.
Click Run  to install the client app and SDK on your test device

This should deploy the client and SDK in one go, and launch the client app. There is a known issue around this in the current release of Flamingo that will be addressed in a following release.

**Comment by hellosagar** [comment]
Thanks for the quick response. I've set the default starting activity to MainActivity for the `client-app`, but I still face the same error.

Here, is the image where I set the specified activity
<img width="1114" alt="Screenshot 2022-10-01 at 10 25 27 PM" src="https://user-images.githubusercontent.com/50016799/193419945-319e4ac3-1264-4385-8701-b1104ee55c7a.png">


Here is the error:
```

10/01 22:23:48: Launching 'client-app' on Pixel 4 API TiramisuPrivacySandbox.
Installation did not succeed.
The application could not be installed: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED

List of apks:
[0] '/Users/sagarkhurana/AndroidStudioProjects/privacy-sandbox-samples/PrivacySandboxKotlin/client-app/build/intermediates/apk/oem/debug/client-app-oem-debug.apk'
Installation failed due to: 'Failed to commit install session 837804839 with command package install-commit 837804839. Error: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl837804839.tmp/base.apk (at Binary XML file line #67): Depending on multiple versions of SDK library com.example.privacysandbox.provider'
Retry
Failed to launch an application on all devices
```

**Comment by cshmerling** [comment]
Hmm.

Have you made any changes to the project, specifically the client-app manifest? There is a `<uses-sdk-runtime>` tag that should be commented out.

Other than that, I'm assuming you've updated to the latest version of the gradle plugin? You'd probably have gotten a warning when starting the project about some incompatibility if not.

Other other than that, I did just test this with a fresh pull of the repo. I created a new emulator, set my build config like you have yours in the image, and clicked run. But I was using Flamingo Canary 2, which might have some bug fixes. Can you try updating to that?

If all that doesn't work, can you upload your project to GitHub so I can see if I can repro? Your error seems to be related to some build flavors we needed to add, but I'm not able to reproduce the error myself.

**Comment by hellosagar** [comment]
Commenting out the `<uses-sdk-runtime>` worked for me. Thanks  @cshmerling 🙏
