### ISSUE TITLE
When will the missing APIs be implemented?

### ISSUE THREAD

**Issue by WataruSuzuki** [android/privacy-sandbox-samples#5]
Thank you this repository.
I am trying it out some experiments with reference to this one.

I also want to try these APIs.
- `SdkRuntimeManager.registerSdkRuntimeCallback(SdkRuntimeCallback callback,
    Executor executor)`
- `SdkRuntimeManager.sendData(String sdkName, Bundle data)`

https://developer.android.com/design-for-safety/privacy-sandbox/sdk-runtime#app-to-sdk-communications

Will the missing API be implemented in the next preview version?

Thank you

**Comment by fredchung** [comment]
Hi - We're continuing to iterate and release features in Developer Preview releases. As of now, we're on [DP3](https://developer.android.com/design-for-safety/privacy-sandbox/release-notes#current).

For the specific APIs mentioned:
We still need to update the [SDK Runtime proposal](https://developer.android.com/design-for-safety/privacy-sandbox/sdk-runtime#app-to-sdk-communications) on naming, but please have a look at [SdkSandboxManager#loadSdk](https://developer.android.com/design-for-safety/privacy-sandbox/reference/sdksandbox/SdkSandboxManager#loadSdk(java.lang.String,%20android.os.Bundle,%20java.util.concurrent.Executor,%20android.app.sdksandbox.SdkSandboxManager.RemoteSdkCallback)) and the corresponding [sample](https://github.com/android/privacy-sandbox-samples/blob/77e8990420604e63d634447b8d81a6d25aa2bda9/PrivacySandboxKotlin/client-app/src/main/java/com/example/client/MainActivity.kt#L84) on usage. 

Functionality related to `SdkRuntimeManager.sendData(String sdkName, Bundle data)` is not yet available for testing. 

Please follow our announcements on the [Android Developers Blog](https://android-developers.googleblog.com/) or [sign-up](https://services.google.com/fb/forms/privacysandbox/) for our newsletter to receive updates.

Thanks.
