### ISSUE TITLE
Attribution API fails on MeasurementSampleApp - Caller is not authorized

### ISSUE THREAD

**Issue by ozadi3** [android/privacy-sandbox-samples#56]
Hi,
We're trying to test the attribution API using:
- Pixel4 emulator with google play - on developer preview 7
- Pixel6a device with google play - with the latests beta (and updated google play services version)

On both cases, after following all the steps in the documentation, including running:
`adb shell device_config put adservices mdd_measurement_manifest_file_url "{ENROLLMENT_URL}"`

After pressing the register click/view event buttons ends without any action, and we don't get data fired into the server URL we configured.

Logcat shows the following error: `com.google.android.adservices.api    E  Caller is not authorized.`

We follow some instructions on closed issues that look similar, like: https://github.com/android/privacy-sandbox-samples/issues/23 without success

Anything we're missing?

**Comment by shen714** [comment]
We are also being blocked by the exact same issue on both developer preview and beta release. Wondering how could we further debug on this.

Appreciate for any guidance!

**Comment by erintwalsh** [comment]
Hi @ozadi3 and @shen714, 

Would you mind following these steps and then try calling the API again? 

1. Make sure all necessary permissions are declared in the AndroidManifest [as shown on lines 17, 18, and 19 here](https://github.com/android/privacy-sandbox-samples/blob/jetpack-main/AttributionReporting/MeasurementSampleApp/app/src/main/AndroidManifest.xml#L17)

2. Reset your allow list by running the commands
* adb shell device_config delete adservices ppapi_app_allow_list

* adb shell device_config put adservices ppapi_app_allow_list [your app package name]


Note: you will need to use the 'put' command for each app package name you are testing with.

**Comment by ozadi3** [comment]
Hi @shen714 
The latest suggestions didn't work for us as well. We experience the same error as before

**Comment by erintwalsh** [comment]
Hi @shen714 and @ozadi3, we have recently pushed a new update to the sample app. Would you mind trying again and making sure the URLs entered match the ones registered during enrollment? Thank you!!

**Comment by ozadi3** [comment]
Hi,
We're able to get the source and trigger events while using real device/emulator with the preview of **Android UpsideDown Cake**.
Just to verify - There is a time difference (~1hr) between calling register_source & register_trigger and the time the servers actually gets the POST requests - is it by design?

**Comment by erintwalsh** [comment]
@ozadi3 that's great to hear! Yes, the timing is intentional, and will be shortened with the next release. You can also run this command to send the requests faster - `adb shell cmd jobscheduler run -f com.google.android.adservices.api 15`
