### ISSUE TITLE
Attribution API - java.lang.IllegalStateException: Service is not available

### ISSUE THREAD

**Issue by TieUper** [android/privacy-sandbox-samples#57]
crash when i click "registerSource" button ， use the Measurement Sample App。
 
![image](https://user-images.githubusercontent.com/18494629/229013356-653b1b8a-c51c-4483-83c2-ef25f4150842.png)

when i use `adb shell setprop log.tag.adservices VERBOSE && adb logcat -s "adservices"`
the console print：    
![image](https://user-images.githubusercontent.com/18494629/229013901-ead803b5-d2a4-4bd0-ac63-e3a8a1434191.png)

**Comment by cshmerling** [comment]
So there a few a `adb` commands you need to run to enable Attribution. Can you confirm you have run all the following:

```
adb shell device_config delete adservices ppapi_app_allow_list
adb shell device_config put adservices adservice_system_service_enabled true
adb shell device_config put adservices adservice_enabled true
adb shell device_config put adservices adservice_enable_status true
adb shell device_config put adservices global_kill_switch false
```

Also, Attribution will require you to [enroll with the Privacy Sandbox](https://developer.android.com/design-for-safety/privacy-sandbox/setup-device-access?version=preview#post-enrollment) have you completed that step as well?

**Comment by Xue-ln** [comment]
Ok, We are waiting for a reply of the enrollment，thanks for your answer
