### ISSUE TITLE
Setup is not working for AGP (Android gradle plugin) version 4.2.0 or lower

### ISSUE THREAD

**Issue by pm-vishal-chougule** [android/privacy-sandbox-samples#6]
I was exploring the SDK Runtime API's and found a couple of setups issues

- While building the application with the provided setup steps, <sdk-library> is not available for the current compiled SDK version
   Error : AndroidManifest.xml:18: AAPT: error: unexpected element <sdk-library> found in <manifest><application>.
- It does not let you install the app into the Tiramisu Android Privacy sandbox emulator by saying incompatible target SDK for the Android emulator.
  Error:
    The installation did not succeed.
    The application could not be installed: INSTALL_FAILED_OLDER_SDK
    The application's minSdkVersion is newer than the device API level

Note: Emulator : Pixel 4 with play service and image: TiramisuPrivacySandbox x86_64

**Comment by fredchung** [comment]
Hi - Are you able to update to the latest stable Android Studio / Android Gradle Plug-in / build-tools? The manifest merger has been updated in recent versions to properly handle this.
