### ISSUE TITLE
Getting an error while trying to build the sample project

### ISSUE THREAD

**Issue by orishema88** [android/privacy-sandbox-samples#67]
I've tried to build the suggested branches with no success. i'm getting the same error:
Unable to proceed generating shim with no provided sdk descriptor entries in: /Users/orishema/AndroidStudioProjects/privacy-sandbox-samples/PrivacySandboxKotlin/example-sdk/build/intermediates/stub_jar/single/sdk-interface-descriptors.jar.Privacy Sandbox Sdk modules require at least one service declaration.

please advice.
Thanks

**Comment by Andrey-Morenkov** [comment]
Hi @orishema88 

Seems there is an answer in one of closed issues:
https://github.com/android/privacy-sandbox-samples/issues/55#issuecomment-1478050156

Working for me

**Comment by orishema88** [comment]
It worked. Thanks!
