### ISSUE TITLE
Unable to get verbose debugging reports for Attribution Reporting API.

### ISSUE THREAD

**Issue by shen714** [android/privacy-sandbox-samples#68]
Hi,

We are testing the ARA and set up the verbose debugging endpoint as per [instructions](https://developer.android.com/design-for-safety/privacy-sandbox/attribution#verbose-debugging). We have tested it on Chrome and it works fine, however we couldn't receive any report when testing ARA on Android. 

Based on the log we should have at least one successful source registration(please correct me if I misunderstood the log message), and we think we are suppose to receive the debugging report of '[source-success](https://github.com/WICG/attribution-reporting-api/blob/main/verbose_debugging_reports.md#source-success)' type? 
<img width="1123" alt="image" src="https://github.com/android/privacy-sandbox-samples/assets/31877911/de949c55-acef-4411-9cdc-60f932d8d3ad">

Any guidance on how to debug further would appreciated! 

p.s.
* We have put "debug_reporting":true in our server response.
* We are using UpsideDownCake extension 6.
<img width="365" alt="image" src="https://github.com/android/privacy-sandbox-samples/assets/31877911/2fae25c1-f015-4c66-9143-9a752a35f206">

**Comment by erintwalsh** [comment]
Hi Shen, verbose debugging for Attribution Reporting won't be available on Android until the end of June. You can find that information and other feature updates on [this spreadsheet](https://docs.google.com/spreadsheets/d/e/2PACX-1vSQ7GBh0Vo4MsL1NkbG7Csznawr-WboqwAtWdk80tajA4yaZ8nDM6DNa0e9563LbT652EjDFW50RLy9/pubhtml).
