### ISSUE TITLE
Java Demo is not rendering the WebView

### ISSUE THREAD

**Issue by EitanSchwartz** [android/privacy-sandbox-samples#7]
I work for a big content delivery company. **Our product heavily relies on rendering content in a WebView.** Unfortunately, I cannot make a WebView render in Privacy Sandbox environment. The bug is opened here since the official demo code does not render a WebView either. (Attaching file logs from both App process & SDK process):

It seems there's some contradiction. 
**On one hand:**
- This demo code comes, pre-built with a WebView rendering example
-  The Privacy Sandbox Developer Preview 1 release notes (April 28, 2022) clearly state:
    "An SDK can render WebView-based banner ads or content in the SDK Runtime." (Source: https://developer.android.com/design-for-safety/privacy-sandbox/release-notes#p1-features)

**On the other hand:**
- The demo fails to render the WebView (AS v.: 2021.2.1.Patch1 , Emulator Pixel4, OS Image: TiramisuPrivacySandbox/arm64-v8a)
-  Other PrivacySandbox official documentation states: ".. however, the SDK Runtime's rendering protections afforded to typical WebView rendering by SDKs will likely not be possible. This is an active area of investigation." (Source: https://developer.android.com/design-for-safety/privacy-sandbox/sdk-runtime#goals)
[NoWebView_AppSide.txt](https://github.com/android/privacy-sandbox-samples/files/8907364/NoWebView_AppSide.txt)
[NoWebView_SDKSide.txt](https://github.com/android/privacy-sandbox-samples/files/8907365/NoWebView_SDKSide.txt)

I can't understand why this is not working, I would love some feedback/acknowledgement/support or if anyone can make this work for them.

**Comment by cshmerling** [comment]
Hello!

Can you please capture a bug report on the device after experiencing the issue? You can capture this by running 
`$ adb bugreport`
in the terminal.

Then please file an issue at [issuetracker](https://issuetracker.google.com/issues/new?component=1116743&template=1629474) and include the bugreport you generated.

**Comment by EitanSchwartz** [comment]
@cshmerling np, I opened an issue and uploaded the bugreport to: https://drive.google.com/drive/folders/1pMpRgf9hlplzAeCxCnr1ZAZpdoZNEWwv?usp=sharing

**Comment by cshmerling** [comment]
Sorry for the radio silence on this issue for awhile- it is getting looked at.
In the meantime, can you try this with the latest Privacy Sandbox image and let me know if it still repros?

**Comment by cshmerling** [comment]
Hey, we are going to close this due to inactivity. Let us know if you are still encountering this issue and we can take a look again. Thanks!
