### ISSUE TITLE
Attribution API: Get Permission Denial Exception During Source Registration

### ISSUE THREAD

**Issue by longv** [android/privacy-sandbox-samples#70]
Hi Team,

After updating to Developer Preview 8 and trying to register the attribution source, I keep getting this error:
```
Unhandled exception thrown during transaction: java.lang.SecurityException: Permission Denial: opening provider com.android.adservices.service.measurement.registration.AsyncRegistrationContentProvider from ProcessRecord{eb6e04f 20137:com.google.android.adservices.api/u0a246} (pid=20137, uid=10246) that is not exported from UID 10243
```

#### Tested on:

- Emulator with **UpsideDownCakePrivacySandbox** image (**API Level**: UpsideDownCakePrivacySanbox, **ABI**: x86_64, **Type**: Google Play) 
- Real device **Pixel 7** (**Android version**: UpsideDownCakePrivacySandbox, **Build number**: URA8.230510.005)

#### Steps taken:

- Ad services is configured using this [official guide](https://developer.android.com/design-for-safety/privacy-sandbox/setup-api-access?version=preview).
- Device is configured using this [office guide](https://developer.android.com/design-for-safety/privacy-sandbox/setup-device-access?version=preview).
- PlayStore is logged in with APS enrolled account.

Do you know what could be the issue?

**Comment by pazlavi** [comment]
Do you have any updates on this issue? 
I am facing the same exception with Pixel 6 device (UpsideDownCakePrivacySandbox/URA8.230510.005).

**Comment by erintwalsh** [comment]
Hi @longv and @pazlavi, 

This is a known issue on Developer Preview 8 and will be fixed in Developer Preview 9. If this is blocking your testing, we recommend using a Beta release.
