### ISSUE TITLE
Topics API is not available on UpsideDownCakePrivacySandbox emulator

### ISSUE THREAD

**Issue by landyrev** [android/privacy-sandbox-samples#71]
Hey! I'm trying to launch the `TopicsJava` sample app on emulator running on `UpsideDownCakePrivacySandbox` (`dev-preview-main` branch), but keep getting the `Service is not available` error (similar to the #61 issue)

Privacy sandbox is enabled on device (using the `adb shell am start -n com.google.android.adservices.api/com.android.adservices.ui.settings.activities.AdServicesSettingsMainActivity` command)

PPAPI enabled, signature_allow_list set to `*`, `disable_topics_enrollment_check` set to `true`

**Comment by cshmerling** [comment]
Closing this issue since its been open awhile with no updates. Let us know if you have any more issues!
