### ISSUE TITLE
Loading another SDK from sdk-app

### ISSUE THREAD

**Issue by ozadi3** [android/privacy-sandbox-samples#8]
Hi!
The sample is very useful, thx.
Some functionalities doesn't work, and it's challenging to figure if it's by design or not.

I was trying to create a project with:

1. client app
2. sandbox sdk 1 
3. sandbox sdk 2

Flow:
first, client app called `mSdkSandboxManager.loadSdk` in order to load sdk 1 (like the demo provided)
than, sdk 1 called `mSdk1.loadSdk` to load sdk 2 - and it didn't work

Does it mean that sandbox SDKs couldn't load other sandbox SDKs? or it's not implemented yet?

**Comment by cshmerling** [comment]
Hello!

Per the [design proposal](https://developer.android.com/design-for-safety/privacy-sandbox/sdk-runtime#sdk-to-sdk-communications), sandboxed SDKs loading sandboxed SDKs is not currently planned to be supported. However, there is some work being done to investigate how to facilitate SDK<->SDK communication via APIs exposed by the sandbox itself. 

That work is still being investigated, so I would recommend [signing up to receive updates](https://developer.android.com/design-for-safety/privacy-sandbox#sign-up-to-receive-updates) about changes coming to the platform and keep an eye out for this use case being supported.
