### ISSUE TITLE
Serving SurfaceView in RecyclerView

### ISSUE THREAD

**Issue by RomanDorofeyev** [android/privacy-sandbox-samples#94]
I'm trying to understand how to use Sandboxed ads in the feed (RecyclerView) but faced a couple of issues:
1. When the SurfaceView not added to the view tree I got the exception:
```
java.lang.IllegalArgumentException: Field params should have the entry for the key (android.app.sdksandbox.extra.WIDTH_IN_PIXELS) with positive integer value
                 	at android.app.sdksandbox.SdkSandboxManager.requestSurfacePackage(SdkSandboxManager.java:570)
```
As I understand all the fields below are required:
```
            Bundle params = new Bundle();
              params.putInt(EXTRA_WIDTH_IN_PIXELS, mClientView.getWidth());
              params.putInt(EXTRA_HEIGHT_IN_PIXELS, mClientView.getHeight());
              params.putInt(EXTRA_DISPLAY_ID, getDisplay().getDisplayId());
              params.putBinder(EXTRA_HOST_TOKEN, mClientView.getHostToken());
```
The question is how to preload the ad if the SurfaceView is not added to the view tree and those data cannot be retrieved?
2. When the SurfaceView added to the view tree I can see the ad provided by sandboxed SDK in RecyclerView, but once RecyclerView scrolled away the ad item and get back - the SurfaceView is empty.
<img width="362" alt="Screenshot 2024-01-10 at 15 30 32" src="https://github.com/android/privacy-sandbox-samples/assets/23260238/70493f47-e39f-4bdd-bdcd-461b4f056868">
<img width="362" alt="Screenshot 2024-01-10 at 15 30 40" src="https://github.com/android/privacy-sandbox-samples/assets/23260238/fc294608-1d1e-4edf-b9f3-72e72392d77b">
The question is how to restore SurfaceView content when RecyclerView scrolled back?

**Comment by slinny** [comment]
Please refer to  the jetpack UI libraries [link](https://developer.android.com/design-for-safety/privacy-sandbox/sdk-runtime-ui-presentation) to show UI from the SDK runtime instead of using requestSurfacePackage.

**Comment by RomanDorofeyev** [comment]
@slinny is there any samples or detailed docs for that?

**Comment by notmariazoe** [comment]
@RomanDorofeyev have you checked the code in the [dev-preview-main branch](https://github.com/android/privacy-sandbox-samples/tree/dev-preview-main/PrivacySandboxKotlin) of the sample? You should have updated examples there.

**Comment by RomanDorofeyev** [comment]
@notmariazoe I did! But I was checking java repo, probably kotlin is more up-to-date, will check it also. Thanks!

**Comment by notmariazoe** [comment]
Definitely, let me know how it goes.
