### ISSUE TITLE
UpsideDownCakePrivacySandbox Emulator Play services keeping stopping 

### ISSUE THREAD

**Issue by pm-vishal-chougule** [android/privacy-sandbox-samples#99]
Hi Team,
I am exploring the Topics API, for the same I have created UpsideDownCakePrivacySandbox revision 3 device image for the emulator. 
The emulator is starting but after 2-3 mins there is an issue with Play services keeps stopping.
![Screenshot_1707397262](https://github.com/android/privacy-sandbox-samples/assets/39619767/24cb15ba-81fa-4575-8fca-043344fc6d27)
Can you help me solve this issue? is there any alternative or can i downgrade it to revision 2?

**Comment by guybashan** [comment]
I have a similar issue. I didn't used to be in the past. Started to spear in the last few updates.

**Comment by cshmerling** [comment]
Unfortunately this is a [known issue with this release](https://developer.android.com/design-for-safety/privacy-sandbox/release-notes#dp10). There are some workarounds for this issue with physical devices, but let me see if I can find anything about emulators.

**Comment by galomrigal** [comment]
We have the same issue on our Emulator using Pixel 7 and version `UpsideDownCakePrivacySandbox`.
Does this issue happen across all (virtual) devices?

**Comment by cshmerling** [comment]
We have since shipped updates to our emulators and device images, so this issue should no longer be present. Please feel free to re-open if you are experiencing this on up to date devices/emulators
